### ISSUE TITLE
How to connect 2 and more sensors?

### ISSUE THREAD

**Issue by ProNikUp** [pololu/vl53l0x-arduino#10]
How can i connect 2 and more sensors & read data with all sensors?

**Comment by mjs513** [comment]
You may want to check this post out on the forum: https://forum.pololu.com/t/vl53l0x-maximum-sensors-on-i2c-arduino-bus/10845

**Comment by ProNikUp** [comment]
Thank you

**Comment by kevin-pololu** [comment]
It sounds like you got the info you were looking for, but if you still need help getting multiple sensors to work, please post a question on the [Pololu forum](https://forum.pololu.com/).
