### ISSUE TITLE
Sensor on ESP32

### ISSUE THREAD

**Issue by Corvek** [pololu/vl53l0x-arduino#11]
Have you ever had the code working with the ESP32? I have a sensor that functions fine on the ESP8266. Load the single and/or continuous sketch again for the ESP32 and it fails to get anywhere.  There is simply no output on the serial monitor. I did try with and without using external pullup resistors.  I found and loaded an IC2 scanner sketch and once loaded it does recognize the sensor.

Any thoughts?

**Comment by kevin-pololu** [comment]
I realize it's been a while since you opened this issue, but I just tried the latest version of the library and examples on an ESP32 board and didn't see any problems. If you're still working on this and still having trouble, please let me know.
