### ISSUE TITLE
Request for a comment explaining why 1910 was changed to 1320 in setMeasurementTimingBudget

### ISSUE THREAD

**Issue by ssilverman** [pololu/vl53l0x-arduino#19]
https://github.com/pololu/vl53l0x-arduino/blob/22d997afc59625d14c3940d54dfd6d1800efa627/VL53L0X.cpp#L427

Would you mind adding a comment explaining why this value was changed from 1910?

**Comment by kevin-pololu** [comment]
I originally wrote this library based on version 1.0.0 of ST's API, where the corresponding definition in `VL53L0X_set_measurement_timing_budget_micro_seconds()` uses the same value (line 1118 of vl53l0x_api_core.c): `uint32_t StartOverheadMicroSeconds = 1320;`

At the time, I noticed it was different than the the value 1910 used in `VL53L0X_get_measurement_timing_budget_micro_seconds()` and made a note of it in the comment for the line you noted above. It is interesting that the value has been changed to 1910 in version 1.0.2; I wonder if this was a mistake in the earlier versions of the API. It would probably be a good idea for me to take a look at what changed between API version 1.0.0 and the current 1.0.2 and update our library to match.
