### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by elpedriyo** [pololu/vl53l0x-arduino#20]
Hello,

I am trying to use multiple devices with this library, currently with adafruit one I can change the I2c adress with this code: lox.begin(0x30)

But I do not know where to change it here.

Let me know,

Thanks

**Comment by kevin-pololu** [comment]
Take a look at the `setAddress()` function; this is covered in the readme on the front page for the repo. If you have further questions, please post on the [Pololu forum](https://forum.pololu.com/) as the GitHub issues are for keeping track of bugs and improvements in the library itself.
