### ISSUE TITLE
multiple devices

### ISSUE THREAD

**Issue by dyln** [pololu/vl53l0x-arduino#21]
hello, i don't have much experience with i2c connection.

how can i connect 6 different vl53L0x in one bus?

i have tried to connect all of them parallel; 5V, GND, SDA, SCL. it just shows one address, connected 2.2k resistors between main sda , scl cables and 5v, didn't worked also.

am i doing something wrong?

**Comment by kevin-pololu** [comment]
Hi, dyln.

As noted on [the product page](https://www.pololu.com/product/2490) for our VL53L0X carrier:

> The sensor’s 7-bit slave address defaults to 0101001b on power-up. It can be changed to any other value by writing one of the device configuration registers, but the new address only applies until the sensor is reset or powered off. ST provides an [application note](https://www.pololu.com/file/0J1239/VL53L0X-AN4846.pdf) that describes how to use multiple VL53L0X sensors on the same I²C bus by individually bringing each sensor out of reset and assigning it a unique address.

You might find the code in [this older issue](https://github.com/pololu/vl53l0x-arduino/issues/1#issuecomment-245160851) and [this forum thread](https://forum.pololu.com/t/vl53l0x-maximum-sensors-on-i2c-arduino-bus/10845/7) useful. If you want additional help, please post on the Pololu forum, as the GitHub issues are intended for keeping track of problems with and changes to the library itself.

Kevin

**Comment by AnudeepNayakAntariksh** [comment]
I am trying to use two ST vl53l0x boards controlled by arduino uno but i am not able to get data , on serial monitor it is printing 65535.please help

**Comment by kevin-pololu** [comment]
@AnudeepNayakAntariksh, please refer to the resources I linked to in the post above yours. If you want additional help, please post on the [Pololu forum](https://forum.pololu.com/), as the GitHub issues are intended for keeping track of problems with and changes to the library itself.

Also, please do not post the same question in multiple places.
