### ISSUE TITLE
having trouble booting sensor    "failed to boot VL53L0x

### ISSUE THREAD

**Issue by JASimpso** [pololu/vl53l0x-arduino#25]
hi, I recently got a icstation VL53L0x laser distance sensor and when I connect it to an Arduino nano(properly I am pretty sure) I get a "failed to boot Vl53L0x" error message. I am using the adafruit example to test the sensor and get a handle of it for later projects.
my connections are as follows
5v to VCC
ground to ground
SCL to A5
SDA to A4

**Comment by kevin-pololu** [comment]
Hi, JASimpso.

This library and its examples do not print the message "failed to boot Vl53L0x"; it looks like you are probably using the [Adafruit VL53L0X library](https://github.com/adafruit/Adafruit_VL53L0X). If you want help with their library, I suggest posting on [their forum](https://forums.adafruit.com/).

Kevin
