### ISSUE TITLE
Can't use your board with an I2C OLED display

### ISSUE THREAD

**Issue by fmarzocca** [pololu/vl53l0x-arduino#27]
Hi,

I am using POLOLU CJMCU-530 with your library, and it works fine with the examples.
I am also using an SSD1306 I2C OLED display (which is normally working with u8g2 lib) but, as soon as  the sketch runs sensor.init(), the display witches off and doesn't work. The 2 I2C devices (sensor and OLED) are on 2 different addresses.
I am using an Arduino Nano, and I am attaching the schematic.
![htay-schematic](https://user-images.githubusercontent.com/8530030/46350032-f7fdf100-c653-11e8-95a4-6195748c3617.png)

**Comment by ryantm** [comment]
Hi.

These GitHub issues are intended for tracking bugs and feature requests related to the library code. We do product support on our [forums](https://forum.pololu.com/) and via email.

We wrote this library specifically to work with our [VL53L0X carrier board]:https://www.pololu.com/product/2490.  If you are having trouble using it with a different product, you should contact the manufacturer of that product for technical support or for recommended software that works with their device.

- Ryan
