### ISSUE TITLE
Measures done using LONG_RANGE mode of 'Single" example seems reach about 60cm, no more

### ISSUE THREAD

**Issue by wrinkle81** [pololu/vl53l0x-arduino#29]
The test has been done in normal light conditions.
Switching between modes seems don't affect the max range measured

Is it normal?

**Comment by kevin-pololu** [comment]
The effective range of the sensor depends on what it is sensing; a large, reflective object can be sensed from farther away than a small one that does not reflect as much light. If you think your sensor is not performing normally and you would like to troubleshoot it, please post on the [Pololu forum](https://forum.pololu.com/), as the GitHub issues are intended for keeping track of problems with and changes to the library itself (and this seems unlikely to be a problem with the library code right now).
