### ISSUE TITLE
Implementation of software i2c

### ISSUE THREAD

**Issue by joesphan** [pololu/vl53l0x-arduino#47]
Hello! I'm planning on using the vl53l0x with a pro micro, which pins sda and scl are occupied by other interrupt devices. I was wondering is it easy to implement software i2c?

 Thanks in advance

**Comment by kevin-pololu** [comment]
The library doesn't have any built-in support for software I2C, but it probably shouldn't be too hard to modify it to use a software I2C library like [this one](https://github.com/stevemarple/SoftWire). If you decide to try this and need help, please post on the [Pololu forum](https://forum.pololu.com/), which would be a better place for us to help you troubleshoot code.
