### ISSUE TITLE
debugPrint.c error in atmega2560

### ISSUE THREAD

**Issue by FranciscoRibeiro29** [pololu/vl53l0x-arduino#54]
Hi, 
 
I am using atmel studio 7.0 for the code, however in the library debugPrint.c in function 'void debugInit()' there is an error when I build a solution and says that 'PRR' has not been declared. I don´t know what PRR is doing or what it is so I have no idea on how to proceed. 

 Francisco.

**Comment by kevin-pololu** [comment]
Sorry for the delayed reply, but this library contains neither a file called debugPrint.c nor a function called `debugInit()`, so your issue doesn't appear to be related to this library. If you do find out more and can confirm that it is related, please let us know.
