### ISSUE TITLE
float value in readRangeContinuousMillimeters

### ISSUE THREAD

**Issue by rorkyendo** [pololu/vl53l0x-arduino#55]
hi i had to get floating value in milimeters like 35.40mm or 45.30mm
but this sensor only getting in integer value like 35mm and 45mm

did this sensor working in floating value?

**Comment by kevin-pololu** [comment]
By default, the VL53L0X gives measurements with a resolution of 1 mm. ST's [VL53L0X API](https://www.st.com/content/st_com/en/products/embedded-software/imaging-software/stsw-img005.html) includes a `RangeFractionalEnable` setting that suggests you might be able to get a smaller resolution, but I have not been able to find much documentation about this setting, and at the moment we have no plans to support it in this library. If you want to try using the ST API directly to get fractional readings, you might try asking on the [ST Community site](https://community.st.com/s/topic/0TO0X000000BSqxWAG/time-of-flight-sensors) for help.
