### ISSUE TITLE
Xtalk issue

### ISSUE THREAD

**Issue by kondoudesu45** [pololu/vl53l0x-arduino#6]
Thank you for your fine work.
Now I have known that it was necessary to set Xtalk compensation with cover window. 
Though I also read  some documents about STM api, it was too difficult to understand it.
Could you add the code about setting that?
Many thanks

**Comment by ryantm** [comment]
Hi, @kondoudesu45.

Sorry for the very late reply. Unfortunately, we do not plan to add this feature to the library.

Sincerely,
Ryan Mulligan
